"""
phase3/adapter_encryptor.py  —  Step 4
-----------------------------------------
Encrypts the Phase 2 LoRA adapter directory or file into a single encrypted
artefact (``adapter.enc``) using AES-256-GCM authenticated encryption.

Workflow
~~~~~~~~
1. If the input is a **directory** (typical PEFT output), it is first archived
   into a deterministic tar.gz in a secure temporary location.
2. The archive (or single file) is encrypted with AES-256-GCM using a fresh
   96-bit nonce generated by ``os.urandom``.
3. The ciphertext is written atomically: we write to a ``*.tmp`` sibling first,
   then ``os.replace()`` it to the final path.  If anything fails, the ``*.tmp``
   file is removed — no half-written encrypted output survives.
4. Encryption metadata is saved alongside the ciphertext as a JSON file.
5. The temporary plaintext archive (if created) is securely shredded after use.

File format
~~~~~~~~~~~
::

    [ nonce (12 bytes) ][ ciphertext + GCM tag (variable) ]

The nonce is prepended to the ciphertext so it can be extracted during
decryption without a separate metadata read.  The GCM tag is appended by
the ``cryptography`` library automatically (last 16 bytes of ciphertext).

Security notes
~~~~~~~~~~~~~~
* ``os.urandom`` produces cryptographically secure nonces.
* AES-256-GCM guarantees both confidentiality and integrity in a single pass.
* No intermediate plaintext is ever left on disk after encryption.
"""

import hashlib
import json
import logging
import os
import shutil
import tarfile
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

logger = logging.getLogger(__name__)

# GCM nonce length (bytes) — 96 bits is the recommended size for AES-GCM.
_NONCE_BYTES = 12


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _archive_directory(source_dir: Path, dest_tar: Path) -> None:
    """
    Creates a deterministic, reproducible tar.gz from ``source_dir``.
    Entries are sorted by name so the archive is bit-for-bit identical
    across runs (given the same source content).
    """
    with tarfile.open(dest_tar, "w:gz") as tar:
        for entry in sorted(source_dir.rglob("*")):
            tar.add(entry, arcname=entry.relative_to(source_dir.parent))
    logger.debug("Archived adapter directory → %s (%d bytes)", dest_tar.name, dest_tar.stat().st_size)


def _encrypt_file(plaintext_path: Path, output_path: Path, key: bytes) -> tuple[str, str]:
    """
    Encrypts ``plaintext_path`` into ``output_path`` with AES-256-GCM.

    Returns
    -------
    tuple[str, str]
        ``(nonce_hex, sha256_of_plaintext)``  — the nonce is needed for
        decryption; the plaintext hash is recorded in metadata for reference.
    """
    nonce = os.urandom(_NONCE_BYTES)
    aesgcm = AESGCM(key)

    plaintext = plaintext_path.read_bytes()
    ciphertext = aesgcm.encrypt(nonce, plaintext, associated_data=None)

    # Compute plaintext hash before writing (for metadata reference only —
    # this is NOT the integrity hash of the encrypted file, which is computed
    # separately in integrity.py).
    plaintext_sha256 = hashlib.sha256(plaintext).hexdigest()

    # Atomic write: tmp → rename
    tmp_path = output_path.with_suffix(".tmp")
    try:
        tmp_path.write_bytes(nonce + ciphertext)
        os.replace(tmp_path, output_path)
    except Exception:
        tmp_path.unlink(missing_ok=True)
        raise

    logger.info("Encrypted adapter → %s (%d bytes)", output_path.name, output_path.stat().st_size)
    return nonce.hex(), plaintext_sha256


def _secure_delete(path: Path, passes: int = 3) -> None:
    """
    Overwrites ``path`` with random bytes (``passes`` times) before unlinking.
    Provides rudimentary defence against trivial file-recovery tools.
    """
    if not path.exists():
        return
    size = path.stat().st_size
    try:
        with open(path, "r+b", buffering=0) as f:
            for _ in range(passes):
                f.seek(0)
                f.write(os.urandom(size))
                os.fsync(f.fileno())
    except OSError:
        pass
    finally:
        path.unlink(missing_ok=True)
    logger.debug("Securely deleted temporary plaintext: %s", path.name)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def encrypt_adapter(
    adapter_input: Path,
    output_enc_path: Path,
    key: bytes,
    fingerprint_hash: str,
    metadata_path: Optional[Path] = None,
) -> dict:
    """
    Encrypts the LoRA adapter at ``adapter_input`` and writes the ciphertext
    to ``output_enc_path``.

    Parameters
    ----------
    adapter_input : Path
        Path to the Phase 2 adapter — either a single file or a directory.
    output_enc_path : Path
        Where to write ``adapter.enc``.
    key : bytes
        32-byte AES-256 key (device-bound, derived by ``key_derivation``).
    fingerprint_hash : str
        Hex digest of the device fingerprint (recorded in metadata).
    metadata_path : Path | None
        If provided, encryption metadata is serialised to this JSON file.

    Returns
    -------
    dict
        Encryption metadata dictionary (same content as the JSON file).

    Raises
    ------
    FileNotFoundError
        If ``adapter_input`` does not exist.
    ValueError
        If ``key`` is not 32 bytes.
    """
    if not adapter_input.exists():
        raise FileNotFoundError(f"Adapter input not found: {adapter_input}")
    if len(key) != 32:
        raise ValueError(f"Key must be 32 bytes for AES-256; got {len(key)}.")

    output_enc_path.parent.mkdir(parents=True, exist_ok=True)

    tmp_archive: Optional[Path] = None
    plaintext_target: Path

    try:
        if adapter_input.is_dir():
            # Archive the directory to a secure temp file.
            tmp_fd, tmp_str = tempfile.mkstemp(suffix=".tar.gz", prefix="p3_adapter_")
            os.close(tmp_fd)
            tmp_archive = Path(tmp_str)
            _archive_directory(adapter_input, tmp_archive)
            plaintext_target = tmp_archive
            adapter_format = "directory:tar.gz"
        else:
            plaintext_target = adapter_input
            adapter_format = f"file:{adapter_input.suffix or 'bin'}"

        nonce_hex, plaintext_sha256 = _encrypt_file(plaintext_target, output_enc_path, key)

    finally:
        # Shred the temp archive — the original directory is untouched.
        if tmp_archive is not None:
            _secure_delete(tmp_archive)

    metadata = {
        "algorithm": "AES-256-GCM",
        "nonce_hex": nonce_hex,
        "adapter_format": adapter_format,
        "plaintext_sha256_ref": plaintext_sha256,
        "fingerprint_hash_ref": fingerprint_hash,
        "version": "3.0.0",
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
    }

    if metadata_path is not None:
        tmp_meta = metadata_path.with_suffix(".tmp")
        try:
            tmp_meta.write_text(json.dumps(metadata, indent=2))
            os.replace(tmp_meta, metadata_path)
        except Exception:
            tmp_meta.unlink(missing_ok=True)
            raise
        logger.info("Encryption metadata saved → %s", metadata_path.name)

    return metadata


def decrypt_adapter(
    enc_path: Path,
    output_path: Path,
    key: bytes,
) -> None:
    """
    Decrypts ``enc_path`` into ``output_path`` using the provided AES-256-GCM key.

    This is the **inverse** of ``encrypt_adapter``.  It is used by the verifier
    to restore the adapter on the authorised device.

    Parameters
    ----------
    enc_path : Path
        Path to ``adapter.enc``.
    output_path : Path
        Where to write the decrypted plaintext (single file or tar.gz).
    key : bytes
        32-byte AES-256 key; must match the key used during encryption.

    Raises
    ------
    ValueError
        On AES-GCM authentication failure (wrong key or tampered ciphertext).
    FileNotFoundError
        If ``enc_path`` does not exist.
    """
    if not enc_path.exists():
        raise FileNotFoundError(f"Encrypted adapter not found: {enc_path}")
    if len(key) != 32:
        raise ValueError(f"Key must be 32 bytes; got {len(key)}.")

    raw = enc_path.read_bytes()
    nonce = raw[:_NONCE_BYTES]
    ciphertext = raw[_NONCE_BYTES:]

    aesgcm = AESGCM(key)
    try:
        plaintext = aesgcm.decrypt(nonce, ciphertext, associated_data=None)
    except Exception as exc:
        raise ValueError(
            "AES-GCM decryption failed. The key is wrong, or the ciphertext has been tampered with."
        ) from exc

    output_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_out = output_path.with_suffix(".tmp")
    try:
        tmp_out.write_bytes(plaintext)
        os.replace(tmp_out, output_path)
    except Exception:
        tmp_out.unlink(missing_ok=True)
        raise

    logger.info(
        "Adapter decrypted successfully → %s (%d bytes)",
        output_path.name,
        output_path.stat().st_size,
    )
